CREATE TABLE DBUPDATE
(
	LASTUPDATE SMALLINT CONSTRAINT PK_MYRES PRIMARY KEY 
);

CREATE TABLE USERDESKTOP
(
	USERCODE  VARCHAR(20),
	SHORTCUTNAME VARCHAR(50),
	COMMANDID	DOUBLE,
	MYCOMMAND	INT,
	OBRECT VARCHAR(20),
	DESCRIPTION VARCHAR(255),
	SHELLCOMMAND VARCHAR(100),
	ICONFILE VARCHAR(200),
	SHORTTEXT VARCHAR(50)
);

CREATE UNIQUE INDEX PK_USERDESKTOP ON USERDESKTOP
(USERCODE,SHORTCUTNAME) WITH PRIMARY;

CREATE TABLE DBCONNECTION
(
	SERVER_DSN 	VARCHAR(40),
	DATABASE_NAME	VARCHAR(40),
	COMPANY_NAME	VARCHAR(100),
	PROVIDER	VARCHAR(40),
	PROMPT		VARCHAR(40)
);

CREATE TABLE MYRESOURCE
(
	KEYCODE VARCHAR(40) CONSTRAINT PK_MYRES PRIMARY KEY ,
	MENUID	DOUBLE,
	THAIRES VARCHAR(50),
	ENGRES VARCHAR(50),
	USERRES1 VARCHAR(50),
	USERRES2 VARCHAR(50),
 	USERRES3 VARCHAR(50),
	CREATORNAME VARCHAR(20)
);

CREATE INDEX MYRESOURCE_ID ON MYRESOURCE ( MENUID );

CREATE TABLE TIPSHELP
(
	HELPKEY	VARCHAR(40) ,
	CONTROLID DOUBLE,
	FIELDNAME VARCHAR(30),
	FIELDNAME_ENG VARCHAR(30),
	DESCRIPTION VARCHAR(255),
	DESCRIPTION_ENG VARCHAR(255)
);

CREATE UNIQUE INDEX PK_TIPSHELP ON TIPSHELP
(HELPKEY,CONTROLID) WITH PRIMARY;

CREATE TABLE USERSHORTCUT
(
	USERCODE VARCHAR(10),
	COMMANDID DOUBLE,
	NAME	VARCHAR(40),
	ITEMNO SMALLINT,
	SHORTCUTNAME VARCHAR(50),
	OBRECT  VARCHAR(20),
	DESCRIPTION  VARCHAR(255),
	SHELLCOMMAND  VARCHAR(100),
	ICONFILE   VARCHAR(100),
	SHORTTEXT     VARCHAR(50)
);

CREATE UNIQUE INDEX PK_SHORTCUT ON USERSHORTCUT
(USERCODE,ITEMNO) WITH PRIMARY;

CREATE TABLE BCUSER
(
	CODE	VARCHAR(40) CONSTRAINT PK_USERCODE PRIMARY KEY ,
	USERNO SMALLINT,
	NAME	VARCHAR(50),
	COMMENT VARCHAR(100),
	BCOPTION1	SMALLINT,
	BCOPTION2	SMALLINT,
	BCOPTION3	SMALLINT,
	BCOPTION4	SMALLINT,
	BCOPTION5	SMALLINT,
	BCOPTION6	SMALLINT,
	BCOPTION7	SMALLINT,
	BCOPTION8	SMALLINT,
	BCOPTION9	SMALLINT,
	BCOPTION10	SMALLINT,
	BCOPTION11	SMALLINT,
	BCOPTION12	SMALLINT,
	BCOPTION13	SMALLINT,
	BCOPTION14	SMALLINT,
	BCOPTION15	SMALLINT,
	BCOPTION16	SMALLINT, 
	BCOPTION17	SMALLINT,
	BCOPTION18	SMALLINT,
	BCOPTION19	SMALLINT,
	BCOPTION20	SMALLINT,
	DEBTPASSWORD VARCHAR(30),
	PICFILENAME	VARCHAR(100),
	DBUSERTYPE VARCHAR(100),
	UGROUP VARCHAR(10)
);

CREATE INDEX USER_NO ON BCUSER ( USERNO );

CREATE TABLE BCUSERGROUP
(
	CODE	VARCHAR(10) CONSTRAINT PK_BCUGROUP PRIMARY KEY ,
	NAME	VARCHAR(50), 
	BCOPTION1	SMALLINT,
	BCOPTION2	SMALLINT,
	BCOPTION3	SMALLINT,
	BCOPTION4	SMALLINT,
	BCOPTION5	SMALLINT,
	BCOPTION6	SMALLINT,
	BCOPTION7	SMALLINT,
	BCOPTION8	SMALLINT,
	BCOPTION9	SMALLINT,
	BCOPTION10	SMALLINT,
	BCOPTION11	SMALLINT,
	BCOPTION12	SMALLINT,
	BCOPTION13	SMALLINT,
	BCOPTION14	SMALLINT,
	BCOPTION15	SMALLINT,
	BCOPTION16	SMALLINT, 
	BCOPTION17	SMALLINT,
	BCOPTION18	SMALLINT,
	BCOPTION19	SMALLINT,
	BCOPTION20	SMALLINT	
);

CREATE TABLE USERSHORTWORD
(
	CODE	VARCHAR(10) CONSTRAINT PK_USERSHORTW PRIMARY KEY ,
	NAME	VARCHAR(40)
);

CREATE TABLE USERWORDHISTORY 
(
	USERCODE VARCHAR (10)  CONSTRAINT PK_USERWORDH PRIMARY KEY ,
	SHORTWORD VARCHAR (40)  
) ;

CREATE TABLE USERAUTHORIZATION 
(
	CODE VARCHAR (40),
	UGROUP VARCHAR (10),
	MENUID DOUBLE NULL ,
	ISMAKE SMALLINT ,
	ISDELETE SMALLINT ,
	ISINSERT SMALLINT ,
	ISEDIT SMALLINT 
) ;

CREATE TABLE GROUPAUTHORIZATION 
(
	CODE VARCHAR (40) ,
	MENUID DOUBLE NULL ,
	ISMAKE SMALLINT ,
	ISDELETE SMALLINT ,
	ISINSERT SMALLINT ,
	ISEDIT SMALLINT 
) ;

CREATE TABLE BCREPORTWRITER
(
	REPNAME	VARCHAR(150) CONSTRAINT PK_REPWRT PRIMARY KEY ,
	USERREMARK	VARCHAR(255),
	SQLSCRIPT	VARCHAR(255),
	FIELDBREAK	VARCHAR(255),
	FIELDSUMMERY VARCHAR(255)
);

CREATE TABLE BCREPORTWRTVAR
(
	REPNAME	VARCHAR(150),
	VARNAME	VARCHAR(50),
	DBTYPE	SMALLINT,
	VARREMARK VARCHAR(100)
);

CREATE TABLE DDEDATA
(
	ALIAS	VARCHAR(20) CONSTRAINT PK_DDEDATA  PRIMARY KEY ,
	DEFAULDB	  SMALLINT,
	SERVERNAME	VARCHAR(50),
	DATABASENAME	 VARCHAR(100),
	USERID		VARCHAR(30),
	PASSWORD		VARCHAR(30),
	MYDESCRIPTION	VARCHAR(255),
	PROVIDER 	VARCHAR(40)
);
CREATE TABLE DDEVAR
(
	VARCODE		VARCHAR(50) CONSTRAINT PK_DDEVAR PRIMARY KEY,
	VARFIELD		VARCHAR(50),
	MYDESCRIPTION	VARCHAR(255)
);

CREATE TABLE DDECOMMAND
(
	TOPIC		VARCHAR(50) CONSTRAINT PK_DDECOMMAND PRIMARY KEY,
	COMMANDTEXT1	VARCHAR(255),
	COMMANDTEXT2	VARCHAR(255),
	COMMANDTEXT3	VARCHAR(255),
	MYDESCRIPTION	VARCHAR(255),
	MYTYPE 		INT
		
);

